# Repris de ~/.config/termite/config

font_family      Source Code Pro
font_size        11.0

enable_audio_bell    no
mouse_hide_wait      3.0
scrollback_lines     -1
cursor_shape         beam
open_url_with        default

# Nord (https://github.com/arcticicestudio/nord)
foreground            #D8DEE9
background            #2E3440
selection_foreground  #D8DEE9
selection_background  #4C566A
cursor                #D8DEE9
cursor_text_color     #2E3440
url_color             #88C0D0

color0   #3B4252
color1   #BF616A
color2   #A3BE8C
color3   #EBCB8B
color4   #81A1C1
color5   #B48EAD
color6   #88C0D0
color7   #E5E9F0
color8   #4C566A
color9   #BF616A
color10  #A3BE8C
color11  #EBCB8B
color12  #81A1C1
color13  #B48EAD
color14  #8FBCBB
color15  #ECEFF4
